# Previsão de sucesso de filmes
Este é um código que realiza a previsão de sucesso de filmes com base no aprendizado de máquina, usando uma base de dados com mais de 800 filmes para o treino dos modelos.

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
tabela = pd.read_csv("movie_success_rate.csv")

display(tabela)

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,...,Music,Musical,Mystery,Romance,Sci-Fi,Sport,Thriller,War,Western,Success
0,1.0,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014.0,121.0,8.10000,757074.0000,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1,2.0,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012.0,124.0,7.00000,485820.0000,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,3.0,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016.0,117.0,7.30000,157606.0000,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,4.0,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016.0,108.0,7.20000,60545.0000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5.0,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016.0,123.0,6.20000,393727.0000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
834,995.0,Project X,Comedy,3 high school seniors throw a birthday party t...,Nima Nourizadeh,"Thomas Mann, Oliver Cooper, Jonathan Daniel Br...",2012.0,88.0,6.70000,164088.0000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
835,997.0,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007.0,94.0,5.50000,73152.0000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
836,998.0,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008.0,98.0,6.20000,70699.0000,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
837,1000.0,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016.0,87.0,5.30000,12435.0000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
838,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.81432,193230.2518,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
print(tabela.columns)

print(tabela.info())

Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore', 'Action', 'Adventure', 'Aniimation', 'Biography', 'Comedy',
       'Crime', 'Drama', 'Family', 'Fantasy', 'History', 'Horror', 'Music',
       'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Sport', 'Thriller', 'War',
       'Western', 'Success'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 839 entries, 0 to 838
Data columns (total 33 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                838 non-null    float64
 1   Title               838 non-null    object
 2   Genre               838 non-null    object
 3   Description         838 non-null    object
 4   Director            838 non-null    object
 5   Actors              838 non-null    object
 6   Year                838 non-null    float64
 7   Runtime (Minutes)   838 non-null    float64
 8   Rating              839 non-null    float64
 9   Votes               839 non-null    float64
 10  Revenue (Millions)  839 non-null    float64
 11  Metascore           838 non-null    float64
 12  Action              838 non-null    float64
 13  Adventure           838 non-null    float64
 14  Aniimation          838 non-null    float64
 15  Biography           838 non-null    float64
 16  Comedy              838 non-null    float64
 17  Crime               838 non-null    float64
 18  Drama               838 non-null    float64
 19  Family              838 non-null    float64
 20  Fantasy             838 non-null    float64
 21  History             838 non-null    float64
 22  Horror              838 non-null    float64
 23  Music               838 non-null    float64
 24  Musical             838 non-null    float64
 25  Mystery             838 non-null    float64
 26  Romance             838 non-null    float64
 27  Sci-Fi              838 non-null    float64
 28  Sport               838 non-null    float64
 29  Thriller            838 non-null    float64
 30  War                 838 non-null    float64
 31  Western             838 non-null    float64
 32  Success             838 non-null    float64
dtypes: float64(28), object(5)
memory usage: 216.4+ KB
None

In [4]:
# Removendo valores NA
print(tabela.isna().sum())
tabela = tabela.dropna()

Rank                  1
Title                 1
Genre                 1
Description           1
Director              1
Actors                1
Year                  1
Runtime (Minutes)     1
Rating                0
Votes                 0
Revenue (Millions)    0
Metascore             1
Action                1
Adventure             1
Aniimation            1
Biography             1
Comedy                1
Crime                 1
Drama                 1
Family                1
Fantasy               1
History               1
Horror                1
Music                 1
Musical               1
Mystery               1
Romance               1
Sci-Fi                1
Sport                 1
Thriller              1
War                   1
Western               1
Success               1
dtype: int64

In [5]:
from sklearn.preprocessing import LabelEncoder

# Transformar as colunas de texto em números para o aprendizado da IA
codificador = LabelEncoder()
tabela["Actors"] = codificador.fit_transform(tabela["Actors"])
tabela["Director"] = codificador.fit_transform(tabela["Director"])

In [6]:
# Treinando a IA
y = tabela['Success']

x = tabela.drop(['Success', 'Description', 'Genre', 'Title'], axis = 1)

x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size = 0.25)

In [7]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

modelos = {
  'Regressão Logistica' : LogisticRegression(),
  'k-NN' : KNeighborsClassifier(),
  'SBM' : SVC(),
  'Árvore de Decisão' : RandomForestClassifier()
}

for nome, modelo in modelos.items():
    modelo.fit(x_treino, y_treino)
    y_pred = modelo.predict(x_teste)
    acuracia = accuracy_score(y_teste, y_pred)
    print(f'{nome} : Acurácia = {acuracia:.4f}')

Regressão Logistica : Acurácia = 0.9238
k-NN : Acurácia = 0.8905
SBM : Acurácia = 0.9143
Árvore de Decisão : Acurácia = 0.9952

D:\Programas\Nova pasta\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [8]:
#Dados fictícios de novos filmes
novo_filme1 = pd.DataFrame({
    "Rank": [840],
    "Title": ["Secrets of the Cosmos"],
    "Genre": ["Sci-Fi,Adventure"],
    "Description": ["In a quest to unravel the mysteries of the cosmos, a team of brilliant scientists and explorers must journey to the far reaches of space, facing danger and awe-inspiring discoveries along the way."],
    "Director": ["Alexandra Nguyen"],
    "Actors": ["Natalie Robinson, Ethan Foster, David Chen, Maya Rodriguez"],
    "Year": [2023],
    "Runtime (Minutes)": [137],
    "Rating": [7.9],
    "Votes": [124789],
    "Revenue (Millions)": [215.45],
    "Metascore": [84],
    "Action": [1],
    "Adventure": [1],
    "Aniimation": [0],
    "Biography": [0],
    "Comedy": [0],
    "Crime": [0],
    "Drama": [0],
    "Family": [0],
    "Fantasy": [0],
    "History": [0],
    "Horror": [0],
    "Music": [0],
    "Musical": [0],
    "Mystery": [0],
    "Romance": [0],
    "Sci-Fi": [1],
    "Sport": [0],
    "Thriller": [0],
    "War": [0],
    "Western": [0]
})

novo_filme2 = pd.DataFrame({
    "Rank": [841],
    "Title": ["The Enchanted Quest"],
    "Genre": ["Adventure,Fantasy"],
    "Description": ["In a magical world full of enchantment and danger, a young hero embarks on a quest to save the kingdom from an ancient evil."],
    "Director": ["Isabella Thompson"],
    "Actors": ["Aiden Knight, Emma Stone, Liam Johnson, Olivia Lee"],
    "Year": [2022],
    "Runtime (Minutes)": [120],
    "Rating": [8.3],
    "Votes": [187652],
    "Revenue (Millions)": [312.87],
    "Metascore": [90],
    "Action": [0],
    "Adventure": [1],
    "Aniimation": [0],
    "Biography": [0],
    "Comedy": [0],
    "Crime": [0],
    "Drama": [0],
    "Family": [0],
    "Fantasy": [1],
    "History": [0],
    "Horror": [0],
    "Music": [0],
    "Musical": [0],
    "Mystery": [0],
    "Romance": [0],
    "Sci-Fi": [0],
    "Sport": [0],
    "Thriller": [0],
    "War": [0],
    "Western": [0]
})

novo_filme3 =  pd.DataFrame({
    "Rank": [842],
    "Title": ["Rise of Legends"],
    "Genre": ["Action,Adventure,Sci-Fi"],
    "Description": ["In a futuristic world torn by conflict, a team of heroes must rise against powerful forces to save humanity from the brink of destruction."],
    "Director": ["Michael Anderson"],
    "Actors": ["Ryan Reynolds, Zoe Smith, Jessica Chen, Chris Evans"],
    "Year": [2023],
    "Runtime (Minutes)": [145],
    "Rating": [9.0],
    "Votes": [298746],
    "Revenue (Millions)": [485.23],
    "Metascore": [88],
    "Action": [1],
    "Adventure": [1],
    "Aniimation": [0],
    "Biography": [0],
    "Comedy": [0],
    "Crime": [0],
    "Drama": [0],
    "Family": [0],
    "Fantasy": [0],
    "History": [0],
    "Horror": [0],
    "Music": [0],
    "Musical": [0],
    "Mystery": [0],
    "Romance": [0],
    "Sci-Fi": [1],
    "Sport": [0],
    "Thriller": [0],
    "War": [0],
    "Western": [0]
})

# Concatenar os DataFrames
filmes_df = pd.concat([novo_filme1, novo_filme2, novo_filme3], ignore_index=True)


# Salva o DataFrame como um arquivo CSV
filmes_df.to_csv("filme_ficticio.csv", index=False)

In [9]:
filme = pd.read_csv("filme_ficticio.csv")
display(filme)

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,...,Horror,Music,Musical,Mystery,Romance,Sci-Fi,Sport,Thriller,War,Western
0,840,Secrets of the Cosmos,"Sci-Fi,Adventure",In a quest to unravel the mysteries of the cos...,Alexandra Nguyen,"Natalie Robinson, Ethan Foster, David Chen, Ma...",2023,137,7.9,124789,...,0,0,0,0,0,1,0,0,0,0
1,841,The Enchanted Quest,"Adventure,Fantasy",In a magical world full of enchantment and dan...,Isabella Thompson,"Aiden Knight, Emma Stone, Liam Johnson, Olivia...",2022,120,8.3,187652,...,0,0,0,0,0,0,0,0,0,0
2,842,Rise of Legends,"Action,Adventure,Sci-Fi","In a futuristic world torn by conflict, a team...",Michael Anderson,"Ryan Reynolds, Zoe Smith, Jessica Chen, Chris ...",2023,145,9.0,298746,...,0,0,0,0,0,1,0,0,0,0

In [10]:
#Deixando essa nova base igual a original
filme["Actors"] = codificador.fit_transform(filme["Actors"])
filme["Director"] = codificador.fit_transform(filme["Director"])

filme = filme.drop(['Description', 'Genre'], axis = 1)

In [11]:
 # Loop para cada filme
for index, row in filme.iterrows():
    print(f'Nome do filme: {row["Title"]}')
    
    # Loop para cada modelo
    for nome, modelo in modelos.items():
        filme_data = row.drop("Title")  # Remove a coluna "Title" dos dados do filme
        filme_data = filme_data.values.reshape(1, -1)  # Converte para o formato de uma única amostra
        prediction = modelo.predict(filme_data)
        sucesso = "Filme vai ser um sucesso!" if prediction[0] == 1 else "Filme não vai ser um sucesso"
        print(f'Previsão de {nome} para o filme: {sucesso}')
    
    print()

Nome do filme: Secrets of the Cosmos
Previsão de Regressão Logistica para o filme: Filme não vai ser um sucesso
Previsão de k-NN para o filme: Filme não vai ser um sucesso
Previsão de SBM para o filme: Filme não vai ser um sucesso
Previsão de Árvore de Decisão para o filme: Filme não vai ser um sucesso

Nome do filme: The Enchanted Quest
Previsão de Regressão Logistica para o filme: Filme vai ser um sucesso!
Previsão de k-NN para o filme: Filme não vai ser um sucesso
Previsão de SBM para o filme: Filme não vai ser um sucesso
Previsão de Árvore de Decisão para o filme: Filme não vai ser um sucesso

Nome do filme: Rise of Legends
Previsão de Regressão Logistica para o filme: Filme vai ser um sucesso!
Previsão de k-NN para o filme: Filme não vai ser um sucesso
Previsão de SBM para o filme: Filme não vai ser um sucesso
Previsão de Árvore de Decisão para o filme: Filme vai ser um sucesso!

D:\Programas\Nova pasta\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
D:\Programas\Nova pasta\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
D:\Programas\Nova pasta\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
D:\Programas\Nova pasta\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
D:\Programas\Nova pasta\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
D:\Programas\Nova pasta\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
D:\Programas\Nova pasta\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
D:\Programas\Nova pasta\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
D:\Programas\Nova pasta\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
D:\Programas\Nova pasta\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
D:\Programas\Nova pasta\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
D:\Programas\Nova pasta\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(